app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from app import db, login_manager


@login_manager.user_loader
def get_user(ident):
    return User.query.get(int(ident))


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True)
    username = db.Column(db.String(64))
    password_hash = db.Column(db.String(128))
    todo_lists = db.relationship(
        'TodoList', cascade="all, delete-orphan", backref='users')

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def authenticate(self, password):
        return check_password_hash(self.password_hash, password)


class Todo(db.Model):
    __tablename__ = 'todo'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    description = db.Column(db.Text)
    date_created = db.Column(db.TIMESTAMP, default=datetime.utcnow)
    status = db.Column(db.Boolean, default=0)
    deadline = db.Column(db.Date)
    list_id = db.Column(db.Integer, db.ForeignKey('todo_list.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, title, list_id, user_id, deadline=None):
        self.title = title
        self.list_id = list_id
        self.user_id = user_id
        self.deadline = deadline


class TodoList(db.Model):
    __tablename__ = 'todo_list'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    todos = db.relationship(
        'Todo', cascade="all, delete-orphan",
        backref='todo_list', lazy='dynamic')

    def __init__(self, title, user_id):
        self.title = title
        self.user_id = user_id

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField
from wtforms.validators import Required, Optional


class TodoForm(FlaskForm):
    title = StringField('Новая задача', validators=[Required()])
    deadline = DateField('Дата окончания', format="%d.%m.%Y",
                         validators=[Optional()])
    create = SubmitField('Создать')


class ListForm(FlaskForm):
    title = StringField('Новый список', validators=[Required()])
    create = SubmitField('Создать')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_modus import Modus


app = Flask(__name__)
modus = Modus(app)
bootstrap = Bootstrap(app)
manager = Manager(app)
db = SQLAlchemy(app)
login_manager = LoginManager(app)
app.config.from_object('app.config.DefaultConfig')
from .main import main
from .auth import auth
from .utils import utils
app.register_blueprint(main)
app.register_blueprint(auth)
app.register_blueprint(utils)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
import datetime
from . import main
from .forms import TodoForm, ListForm
from ..models import Todo, TodoList
from .. import db, login_manager


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for('auth.login'))


@main.route("/")
def home():
    return render_template('index.html')


@main.route("/list", methods=['GET', 'POST'])
@login_required
def list():
    form = ListForm()
    if form.validate_on_submit():
        user_id = current_user.id
        todo_list = TodoList(form.title.data, user_id)
        db.session.add(todo_list)
        db.session.commit()
        flash('Список добавлен', 'alert alert-success')
        return redirect(url_for('main.list'))
    return render_template('todolist.html', form=form)


@main.route("/list/<int:list_id>", methods=['DELETE'])
@login_required
def list_del(list_id):
    user_id = current_user.id
    todo_list = TodoList.query.filter_by(
        id=list_id, user_id=user_id).first_or_404()
    db.session.delete(todo_list)
    db.session.commit()
    return redirect(url_for('main.list'))


@main.route("/list/<int:list_id>", methods=['PUT'])
@login_required
def list_edit(list_id):
    user_id = current_user.id
    todo_list = TodoList.query.filter_by(
        id=list_id, user_id=user_id).first_or_404()
    todo_list.title = request.args.get('new_title')
    db.session.commit()
    return redirect(url_for('main.list'))


@main.route("/list/<int:list_id>", methods=['GET', 'POST'])
@login_required
def todo(list_id):
    form = TodoForm()
    user_id = current_user.id
    todo_list = TodoList.query.filter_by(
        id=list_id, user_id=user_id).first_or_404()
    # REMAKE: передовать в представления все задачи
    # и там их разбирать
    during = todo_list.todos.order_by(
        (Todo.deadline.desc())).filter(Todo.status == 0).all()
    finished = todo_list.todos.filter(Todo.status == 1).all()
    # !!!
    now = datetime.date.today()
    if form.validate_on_submit():
        todo = Todo(form.title.data, todo_list.id, user_id, form.deadline.data)
        db.session.add(todo)
        db.session.commit()
        flash('Задача добавлена', 'alert alert-success')
        return redirect(url_for('main.todo', list_id=list_id))
    return render_template(
        'todo.html', form=form, todo_list=todo_list,
        finished=finished, during=during, now=now)


@main.route("/list/<int:list_id>/<int:todo_id>", methods=['DELETE'])
@login_required
def todo_del(list_id, todo_id):
    user_id = current_user.id
    todo = Todo.query.filter_by(
        id=todo_id, list_id=list_id, user_id=user_id).first_or_404()
    db.session.delete(todo)
    db.session.commit()
    return redirect(url_for('main.todo', list_id=list_id))


@main.route("/list/<int:list_id>/<int:todo_id>", methods=['PUT'])
@login_required
def todo_edit(list_id, todo_id):
    user_id = current_user.id
    todo = Todo.query.filter_by(
        id=todo_id, list_id=list_id, user_id=user_id).first_or_404()
    todo.title = request.args.get('new_title')
    todo.description = request.args.get('description')
    db.session.commit()
    return redirect(url_for('main.todo', list_id=list_id))


@main.route("/list/<int:list_id>/<int:todo_id>", methods=['PATCH'])
@login_required
def mark_done(list_id, todo_id):
    user_id = current_user.id
    todo = Todo.query.filter_by(
        id=todo_id, list_id=list_id, user_id=user_id).first_or_404()
    if not todo.status:
        todo.status = True
    db.session.commit()
    return redirect(url_for('main.todo', list_id=list_id))

app/utils/__init__.py
from flask import Blueprint

utils = Blueprint('utils', __name__)

from . import errors

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Simple TODO{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('main.home') }}">Simple TODO</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('main.list') }}">TODO</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('auth.logout') }}"><span class="glyphicon glyphicon-log-in"></span> Выход</a></li>
        {% else %}  
          <li><a href="{{ url_for('auth.reg') }}">Регистрация</a></li>
          <li><a href="{{ url_for('auth.login') }}"><span class="glyphicon glyphicon-log-in"></span> Вход</a></li>
        {% endif %}  
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container-fluid text-center">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="{{ category }}">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
    {% if current_user.is_authenticated %}
        <h1>Здравствуйте {{ current_user.username }}!</h1>
    {% else %}
        <h1>Для просмотра списка дел необходима авторизация</h1>
    {% endif %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Авторизация</h1>
</div>
<div class="col-lg-4 col-lg-offset-4 text-center">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Регистрация</h1>
</div>
<div class="col-lg-4 col-lg-offset-4 text-center">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/todo.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/todo-style.css', _external=True) }}">
{% endblock %}
{% block page_content %}
    <div class="col-sm-3 sidenav">
        {{ wtf.quick_form(form) }}
        <h3>Списки</h3>
        <ul class="list-group" id="side_list">
            {% for each in current_user.todo_lists %}
                <li class="list-group-item" id="{% if each.id == todo_list.id %}current{% endif %}">
                    <div>
                        <a class="list-link" href="{{ url_for('main.todo', list_id=each.id) }}">{{ each.title }}</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-sm-9">
        <h1>{{ todo_list.title }}</h1>
        {% if during|length > 0 %}
            <table class="table text-left">
                <thead>
                    <tr>
                        <th>Задача</th>
                        <th>Дата добавления</th>
                        <th>Дата окончания</th>
                    </tr>
                </thead>
                <tbody>
                    {% for each in during %}
                        <tr class="{% if each.deadline and each.deadline <= now %}danger{% endif %}">
                            <td>{{ each.title }}</td>
                            <td>{{ each.date_created.strftime('%d.%m.%Y') }}</td>
                            <td>
                                {% if each.deadline %}
                                    {{ each.deadline.strftime('%d.%m.%Y') }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td>
                                <form action="{{ url_for('main.todo_del', list_id=each.list_id, todo_id=each.id) }}">  
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" class="btn btn-danger">Удалить</button>
                                </form>
                            </td>
                            <td>
                                <button class="btn btn-info" data-toggle="modal" data-target="#{{ each.id }}">
                                    Описание
                                </button>
                                <div class="modal fade" id="{{ each.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                <h4 class="modal-title" id="myModalLabel">Описание задачи "{{ each.title }}"</h4>
                                            </div>
                                            <div class="modal-body">
                                                    <form action="{{ url_for('main.todo_edit', list_id=each.list_id, todo_id=each.id) }}">
                                                        <input type="hidden" name="_method" value="PUT">
                                                        <div class="form-group">
                                                            <label for="new_title">Название</label>
                                                            <input type="text" class="form-control" name="new_title" value="{{ each.title }}">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="description">Описание</label>
                                                            {% if each.description %}
                                                                <textarea class="form-control" rows="3" name="description">{{ each.description }}</textarea>
                                                            {% else %}
                                                                <textarea class="form-control" rows="3" name="description"></textarea>
                                                            {% endif %}    
                                                        </div>    
                                                        <button type="submit" class="btn btn-warning">Сохранить и закрыть</button>
                                                    </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                            </td>
                            <td>
                                <form action="{{ url_for('main.mark_done', list_id=each.list_id, todo_id=each.id) }}">  
                                    <input type="hidden" name="_method" value="PATCH">
                                    <button type="submit" class="btn btn-success">Выполнить</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% elif finished|length < 1 %}
            <h3>В этом списке пока что нет задач</h3>
        {% endif %}
        {% if finished|length > 0 %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Выполненные задачи
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        <table class="table text-left">
                            <thead>
                                <tr>
                                    <th>Задача</th>
                                    <th>Описание</th>
                                    <th>Дата добавления</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for each in finished %}
                                    <tr>
                                        <td><s>{{ each.title }}</s></td>
                                        <td><s>{{ each.description }}</s></td>
                                        <td><s>{{ each.date_created.strftime('%d-%m-%Y') }}</s></td>
                                        <td>
                                            <form action="{{ url_for('main.todo_del', list_id=each.list_id, todo_id=each.id) }}">  
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-danger">Удалить</button>
                                            </form>
                                        </td>
                                        <td>
                                            <form action="{{ url_for('main.mark_done', list_id=each.list_id, todo_id=each.id) }}">  
                                                <input type="hidden" name="_method" value="PATCH">
                                                <button type="submit" class="btn btn-warning">Возобновить</button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endif %}	
    </div>    
{% endblock %}

app/templates/todolist.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="col-sm-3 sidenav">
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-sm-9">
        <h1>Списки</h1>   
        <table class="table text-center">
            <tbody>
                {% for each in current_user.todo_lists %}
                    <tr>
                        <td><h4><a href="{{ url_for('main.todo', list_id=each.id) }}">{{ each.title }}</a></h4></td>
                        <td>
                            <form action="{{ url_for('main.todo', list_id=each.id) }}">
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        </td>
                        <td>
                            <button class="btn btn-info" data-toggle="modal" data-target="#{{ each.id }}">
                                Изменить
                            </button>
                            <div class="modal fade" id="{{ each.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{ url_for('main.todo', list_id=each.id) }}">
                                                <input type="hidden" name="_method" value="PUT">
                                                <div class="form-group">
                                                    <label for="new_title">Название</label>
                                                    <input type="text" class="form-control" name="new_title" value="{{ each.title }}">
                                                </div>    
                                                <button type="submit" class="btn btn-warning">Сохранить и закрыть</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}